/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banco_colas;

import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;

/**
 *
 * @author uresh
 */
public class m1 extends javax.swing.JFrame {

    Cola colita = new Cola();
    int turno = 1;

    static int temporizador = 10;
    private String turnoActual = "0";
    private boolean reclamar;

    /**
     * Creates new form m1
     */
    public m1() {
        //  this.setLocationRelativeTo(null);
        initComponents();

        this.setLocationRelativeTo(null);
        this.txtTurno.setText(null);
        verMenu();

    }

    public m1(Cola coli, String turno) {
        //  this.setLocationRelativeTo(null);
        initComponents();
        this.setLocationRelativeTo(null);
        colita = coli;
        turnoActual = turno;
        this.txtTurno.setText(turno);
        try {
            listTurnos.setModel(colita.imprimir());
        } catch (Exception e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dNext = new javax.swing.JDialog();
        txtTiempo = new javax.swing.JLabel();
        btnReclamar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNext = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dGenera = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtApP = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtApM = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cbAño = new javax.swing.JComboBox<>();
        cbDia = new javax.swing.JComboBox<>();
        cbMes = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        btnCrearCuenta = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        dIngresa = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        btnCrearCuenta1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listTurnos = new javax.swing.JList<>();
        menu1 = new javax.swing.JLayeredPane();
        btnGenera = new javax.swing.JButton();
        btnIngresa = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtTurno = new javax.swing.JLabel();
        btnBoleto = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        dNext.setTitle("!Reclama tu turno");
        dNext.setPreferredSize(new java.awt.Dimension(600, 360));
        dNext.setSize(new java.awt.Dimension(571, 400));
        dNext.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTiempo.setFont(new java.awt.Font("Timotheos", 0, 36)); // NOI18N
        txtTiempo.setForeground(new java.awt.Color(0, 153, 153));
        txtTiempo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTiempo.setText("txt");
        dNext.getContentPane().add(txtTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 560, 50));

        btnReclamar.setBackground(new java.awt.Color(0, 0, 204));
        btnReclamar.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        btnReclamar.setForeground(new java.awt.Color(255, 255, 255));
        btnReclamar.setText("Pasar a ventanilla");
        btnReclamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReclamarActionPerformed(evt);
            }
        });
        dNext.getContentPane().add(btnReclamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Turno");
        dNext.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 550, -1));

        txtNext.setFont(new java.awt.Font("Akbar", 0, 36)); // NOI18N
        txtNext.setForeground(new java.awt.Color(102, 102, 102));
        txtNext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNext.setText("f");
        dNext.getContentPane().add(txtNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 550, 50));

        jLabel3.setBackground(new java.awt.Color(115, 220, 255));
        jLabel3.setText(" ");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(51, 0, 204)));
        jLabel3.setMaximumSize(new java.awt.Dimension(571, 296));
        jLabel3.setMinimumSize(new java.awt.Dimension(571, 296));
        jLabel3.setOpaque(true);
        jLabel3.setPreferredSize(new java.awt.Dimension(571, 296));
        dNext.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 290));

        jLabel4.setText("jLabel4");
        dNext.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, -1, -1));

        jLabel5.setText("jLabel5");
        dNext.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, -1, -1));

        dGenera.setMinimumSize(new java.awt.Dimension(750, 500));
        dGenera.setPreferredSize(new java.awt.Dimension(684, 427));
        dGenera.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Ingresa tus datos");
        dGenera.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 180, 30));

        txtNombre.setBackground(new java.awt.Color(53, 66, 78));
        txtNombre.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(140, 213, 253));
        txtNombre.setText(" ");
        dGenera.getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 330, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 153));
        jLabel9.setText("Apellido Paterno");
        dGenera.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 150, 30));

        txtApP.setBackground(new java.awt.Color(53, 66, 78));
        txtApP.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtApP.setForeground(new java.awt.Color(140, 213, 253));
        txtApP.setText(" ");
        dGenera.getContentPane().add(txtApP, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 330, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 153));
        jLabel10.setText("Apellido Materno");
        dGenera.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 160, 30));

        txtApM.setBackground(new java.awt.Color(53, 66, 78));
        txtApM.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtApM.setForeground(new java.awt.Color(140, 213, 253));
        txtApM.setText(" ");
        dGenera.getContentPane().add(txtApM, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 330, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha de Nacimeinto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16), new java.awt.Color(0, 131, 204))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 153));
        jLabel11.setText("Dia");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 90, 30));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 153));
        jLabel12.setText("Año");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 110, 30));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 153));
        jLabel13.setText("Mes");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 110, 30));

        cbAño.setBackground(new java.awt.Color(53, 66, 78));
        cbAño.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        cbAño.setForeground(new java.awt.Color(140, 213, 253));
        cbAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005" }));
        jPanel2.add(cbAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        cbDia.setBackground(new java.awt.Color(53, 66, 78));
        cbDia.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        cbDia.setForeground(new java.awt.Color(140, 213, 253));
        cbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cbDia.setOpaque(false);
        jPanel2.add(cbDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        cbMes.setBackground(new java.awt.Color(53, 66, 78));
        cbMes.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        cbMes.setForeground(new java.awt.Color(140, 213, 253));
        cbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "enero", "febrero", "marzo", "abril", "mayo", "junio", "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre" }));
        jPanel2.add(cbMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        dGenera.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 510, 110));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 153));
        jLabel14.setText("Nombre");
        dGenera.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 130, 30));

        btnCrearCuenta.setBackground(new java.awt.Color(102, 0, 255));
        btnCrearCuenta.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnCrearCuenta.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearCuenta.setText("Generar Cuenta");
        btnCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCuentaActionPerformed(evt);
            }
        });
        dGenera.getContentPane().add(btnCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 240, 30));

        jLabel15.setBackground(new java.awt.Color(123, 202, 206));
        jLabel15.setText(" ");
        jLabel15.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(0, 102, 102)), "Generar Cuenta", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 24), new java.awt.Color(0, 102, 102))); // NOI18N
        jLabel15.setOpaque(true);
        dGenera.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 430));

        dIngresa.setMinimumSize(new java.awt.Dimension(600, 300));
        dIngresa.setPreferredSize(new java.awt.Dimension(700, 330));
        dIngresa.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 153));
        jLabel16.setText("NIP");
        dIngresa.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 130, 30));

        txtNombre1.setBackground(new java.awt.Color(53, 66, 78));
        txtNombre1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtNombre1.setForeground(new java.awt.Color(140, 213, 253));
        txtNombre1.setText(" ");
        dIngresa.getContentPane().add(txtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 330, -1));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 153, 153));
        jLabel17.setText("No. de Cuenta");
        dIngresa.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 130, 30));

        jPasswordField1.setBackground(new java.awt.Color(53, 66, 78));
        jPasswordField1.setForeground(new java.awt.Color(140, 213, 253));
        dIngresa.getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 330, -1));

        btnCrearCuenta1.setBackground(new java.awt.Color(102, 0, 255));
        btnCrearCuenta1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnCrearCuenta1.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearCuenta1.setText("Ingresar ");
        btnCrearCuenta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCuenta1ActionPerformed(evt);
            }
        });
        dIngresa.getContentPane().add(btnCrearCuenta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 240, 30));

        jLabel6.setBackground(new java.awt.Color(123, 202, 206));
        jLabel6.setText(" ");
        jLabel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(0, 102, 102)), "Ingresar a Cuenta", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 24), new java.awt.Color(0, 102, 102))); // NOI18N
        jLabel6.setOpaque(true);
        dIngresa.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 260));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listTurnos.setBackground(new java.awt.Color(67, 84, 117));
        listTurnos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(3, 2, 3, 2, new java.awt.Color(165, 243, 219)), "Turnos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 0, 16), new java.awt.Color(165, 243, 219))); // NOI18N
        listTurnos.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        listTurnos.setForeground(new java.awt.Color(197, 116, 224));
        jScrollPane1.setViewportView(listTurnos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 16, 140, 410));

        menu1.setBackground(new java.awt.Color(103, 142, 181));
        menu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(165, 243, 219), 5));
        menu1.setOpaque(true);

        btnGenera.setBackground(new java.awt.Color(63, 63, 150));
        btnGenera.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnGenera.setForeground(new java.awt.Color(255, 255, 255));
        btnGenera.setText("Generar cuenta");
        btnGenera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneraActionPerformed(evt);
            }
        });

        btnIngresa.setBackground(new java.awt.Color(63, 63, 150));
        btnIngresa.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnIngresa.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresa.setText("Ingresar cuenta");
        btnIngresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresaActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(255, 51, 51));
        btnSalir.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        menu1.setLayer(btnGenera, javax.swing.JLayeredPane.DEFAULT_LAYER);
        menu1.setLayer(btnIngresa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        menu1.setLayer(btnSalir, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout menu1Layout = new javax.swing.GroupLayout(menu1);
        menu1.setLayout(menu1Layout);
        menu1Layout.setHorizontalGroup(
            menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu1Layout.createSequentialGroup()
                .addGroup(menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menu1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnGenera, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menu1Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(198, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnIngresa, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        menu1Layout.setVerticalGroup(
            menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu1Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(btnGenera, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btnIngresa, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );

        getContentPane().add(menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 16, 520, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(4, 2, 4, 2, new java.awt.Color(255, 255, 255)), "Turno", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Century Gothic", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N

        txtTurno.setFont(new java.awt.Font("Beijing Redux Thick", 0, 100)); // NOI18N
        txtTurno.setForeground(new java.awt.Color(255, 255, 255));
        txtTurno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTurno.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtTurno, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtTurno, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 16, -1, 140));

        btnBoleto.setBackground(new java.awt.Color(102, 0, 255));
        btnBoleto.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnBoleto.setForeground(new java.awt.Color(255, 255, 255));
        btnBoleto.setText("Boleto");
        btnBoleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoletoActionPerformed(evt);
            }
        });
        getContentPane().add(btnBoleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 110, 50));

        jLabel2.setBackground(new java.awt.Color(123, 202, 206));
        jLabel2.setText(" ");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoletoActionPerformed
        boolean check = colita.insertar(turno + "");
        if (check) {
            turno++;
        }
        System.out.println("perro: " + this.txtTurno == null);
        if (this.txtTurno.getText() == null) {
            try {
                turnoActual = colita.eliminar();
            } catch (Exception e) {
                System.out.println("no hay mas en fila");
            }
            txtTurno.setText(turnoActual);
            if (turnoActual == null) {
                siguiente(turnoActual);
            }

        }
        listTurnos.setModel(colita.imprimir());
        verMenu();
    }//GEN-LAST:event_btnBoletoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        txtTurno.setText(null);
        try {
            turnoActual = colita.eliminar();
        } catch (Exception e) {
            System.out.println("no hay mas en fila");
        }
        if (turnoActual != null) {
            txtTurno.setText(turnoActual);
            siguiente(turnoActual);
        }
 verMenu();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnReclamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReclamarActionPerformed
        reclamar = true;
    }//GEN-LAST:event_btnReclamarActionPerformed

    private void btnGeneraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneraActionPerformed
        dGenera.setLocationRelativeTo(null);
        dGenera.setVisible(true);
    }//GEN-LAST:event_btnGeneraActionPerformed

    private void btnCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearCuentaActionPerformed

    private void btnCrearCuenta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCuenta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearCuenta1ActionPerformed

    private void btnIngresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresaActionPerformed
         dIngresa.setLocationRelativeTo(null);
        dIngresa.setVisible(true);
    }//GEN-LAST:event_btnIngresaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(m1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(m1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(m1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(m1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new m1().setVisible(true);
            }
        });
    }

    public void siguiente(String turno) {
        listTurnos.setModel(colita.imprimir());
        reclamar = false;
        dNext.setLocationRelativeTo(null);
        dNext.setVisible(true);
        txtTurno.setText(turno);
        txtNext.setText(turno);
        temporizador = 10;
        Timer t = new Timer();
        t.scheduleAtFixedRate(new TimerTask() {

            @Override
            public void run() {

                temporizador--;

                txtTiempo.setText(" " + temporizador);

                if (reclamar) {
                    t.cancel();
                    dNext.setVisible(false);
                    JOptionPane.showMessageDialog(null, "Has reclamado tu turno");
                }

                if (temporizador == 0) {
                    String aux = turnoActual;
                    t.cancel();

                    turnoActual = colita.eliminar();
                    if (turnoActual == null) {
                        JOptionPane.showMessageDialog(null, "Como no hay nadie mas en fila, puede pasar");
                        //No se hace nada, se cierra 
                        dNext.setVisible(false);
                        turnoActual = aux; //Duda dudosa
                    } else {
                        JOptionPane.showMessageDialog(null, "Lo sentimos, tiempo de espera terminado");
                        dNext.setVisible(false);
                        siguiente(turnoActual);
                    }
                }

            }
        }, 0, 400);
        listTurnos.setModel(colita.imprimir());

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBoleto;
    private javax.swing.JButton btnCrearCuenta;
    private javax.swing.JButton btnCrearCuenta1;
    private javax.swing.JButton btnGenera;
    private javax.swing.JButton btnIngresa;
    private javax.swing.JButton btnReclamar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbAño;
    private javax.swing.JComboBox<String> cbDia;
    private javax.swing.JComboBox<String> cbMes;
    private javax.swing.JDialog dGenera;
    private javax.swing.JDialog dIngresa;
    private javax.swing.JDialog dNext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listTurnos;
    private javax.swing.JLayeredPane menu1;
    private javax.swing.JTextField txtApM;
    private javax.swing.JTextField txtApP;
    private javax.swing.JLabel txtNext;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JLabel txtTiempo;
    private javax.swing.JLabel txtTurno;
    // End of variables declaration//GEN-END:variables

    private void verMenu() {
        if (txtTurno.getText() == null) {
            menu1.setVisible(false);
        } else {
            menu1.setVisible(true);
        }
    }
}
