/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banco_colas;

/**
 *
 * @author uresh
 */
public class m2 extends javax.swing.JFrame {

    Cola colita = new Cola();
    private String turnoActual;

    /**
     * Creates new form m2
     */
    public m2() {
        initComponents();

    }

    public m2(Cola coli, String turno) {
        //  this.setLocationRelativeTo(null);
        initComponents();
        this.setLocationRelativeTo(null);
        colita = coli;
        turnoActual = turno;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dDep = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnDepositar = new javax.swing.JButton();
        lblSaldo = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        sDep = new javax.swing.JSpinner();
        dRet = new javax.swing.JDialog();
        jLabel18 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnRetirar = new javax.swing.JButton();
        lblSaldo1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        sRet = new javax.swing.JSpinner();
        dTran = new javax.swing.JDialog();
        jLabel23 = new javax.swing.JLabel();
        sTran = new javax.swing.JSpinner();
        btnRetirar2 = new javax.swing.JButton();
        lblSaldo3 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        cbTran = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        dEditC = new javax.swing.JDialog();
        btnEdit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        dEditC1 = new javax.swing.JDialog();
        jLabel29 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtApP1 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        btnNip1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        cbAño1 = new javax.swing.JComboBox<>();
        cbDia1 = new javax.swing.JComboBox<>();
        cbMes1 = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        btnEdit1 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        txtApM2 = new javax.swing.JTextField();
        fondo1 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        menu1 = new javax.swing.JLayeredPane();
        btnDep = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnTra = new javax.swing.JButton();
        btnGenera4 = new javax.swing.JButton();
        btnHis = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnRe = new javax.swing.JButton();
        btnEdC = new javax.swing.JButton();

        jLabel15.setBackground(new java.awt.Color(123, 202, 206));
        jLabel15.setText(" ");
        jLabel15.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(0, 102, 102)), "Depositar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 24), new java.awt.Color(0, 102, 102))); // NOI18N
        jLabel15.setOpaque(true);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Ingresa tus datos");

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 153));
        jLabel14.setText("Cantidad a depositar");

        btnDepositar.setBackground(new java.awt.Color(102, 0, 255));
        btnDepositar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnDepositar.setForeground(new java.awt.Color(255, 255, 255));
        btnDepositar.setText("Depositar");
        btnDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositarActionPerformed(evt);
            }
        });

        lblSaldo.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblSaldo.setForeground(new java.awt.Color(51, 0, 102));
        lblSaldo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSaldo.setText("$0.0");

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 153, 153));
        jLabel17.setText("Saldo ");

        sDep.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        sDep.setModel(new javax.swing.SpinnerNumberModel(100, 100, null, 50));

        javax.swing.GroupLayout dDepLayout = new javax.swing.GroupLayout(dDep.getContentPane());
        dDep.getContentPane().setLayout(dDepLayout);
        dDepLayout.setHorizontalGroup(
            dDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dDepLayout.createSequentialGroup()
                .addGroup(dDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dDepLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(sDep)))
                    .addGroup(dDepLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(btnDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(160, Short.MAX_VALUE))
            .addGroup(dDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dDepLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(24, Short.MAX_VALUE)))
            .addGroup(dDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dDepLayout.createSequentialGroup()
                    .addGap(0, 219, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 219, Short.MAX_VALUE)))
            .addGroup(dDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dDepLayout.createSequentialGroup()
                    .addGap(72, 72, 72)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(416, Short.MAX_VALUE)))
        );
        dDepLayout.setVerticalGroup(
            dDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dDepLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(lblSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(dDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(btnDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(dDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dDepLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(dDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dDepLayout.createSequentialGroup()
                    .addGap(0, 167, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 167, Short.MAX_VALUE)))
            .addGroup(dDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dDepLayout.createSequentialGroup()
                    .addGap(98, 98, 98)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(236, Short.MAX_VALUE)))
        );

        jLabel18.setBackground(new java.awt.Color(123, 202, 206));
        jLabel18.setText(" ");
        jLabel18.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(0, 102, 102)), "Retirar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 24), new java.awt.Color(0, 102, 102))); // NOI18N
        jLabel18.setOpaque(true);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Ingresa tus datos");

        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 153, 153));
        jLabel19.setText("Cantidad a retirar");

        btnRetirar.setBackground(new java.awt.Color(102, 0, 255));
        btnRetirar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnRetirar.setForeground(new java.awt.Color(255, 255, 255));
        btnRetirar.setText("Retirar");
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });

        lblSaldo1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblSaldo1.setForeground(new java.awt.Color(51, 0, 102));
        lblSaldo1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSaldo1.setText("$0.0");

        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 153, 153));
        jLabel21.setText("Saldo ");

        sRet.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        sRet.setModel(new javax.swing.SpinnerNumberModel(100, 100, null, 50));

        javax.swing.GroupLayout dRetLayout = new javax.swing.GroupLayout(dRet.getContentPane());
        dRet.getContentPane().setLayout(dRetLayout);
        dRetLayout.setHorizontalGroup(
            dRetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dRetLayout.createSequentialGroup()
                .addGroup(dRetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dRetLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dRetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSaldo1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(sRet)))
                    .addGroup(dRetLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(btnRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(202, Short.MAX_VALUE))
            .addGroup(dRetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dRetLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(24, Short.MAX_VALUE)))
            .addGroup(dRetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dRetLayout.createSequentialGroup()
                    .addGap(0, 219, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 219, Short.MAX_VALUE)))
            .addGroup(dRetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dRetLayout.createSequentialGroup()
                    .addGap(72, 72, 72)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(416, Short.MAX_VALUE)))
        );
        dRetLayout.setVerticalGroup(
            dRetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dRetLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(lblSaldo1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(dRetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sRet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(btnRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(dRetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dRetLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(dRetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dRetLayout.createSequentialGroup()
                    .addGap(0, 167, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 167, Short.MAX_VALUE)))
            .addGroup(dRetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dRetLayout.createSequentialGroup()
                    .addGap(98, 98, 98)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(236, Short.MAX_VALUE)))
        );

        dTran.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 153, 153));
        jLabel23.setText("Saldo ");
        dTran.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 130, 30));

        sTran.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        sTran.setModel(new javax.swing.SpinnerNumberModel(100, 100, null, 50));
        dTran.getContentPane().add(sTran, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 163, -1));

        btnRetirar2.setBackground(new java.awt.Color(102, 0, 255));
        btnRetirar2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnRetirar2.setForeground(new java.awt.Color(255, 255, 255));
        btnRetirar2.setText("Retirar");
        btnRetirar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirar2ActionPerformed(evt);
            }
        });
        dTran.getContentPane().add(btnRetirar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 240, 30));

        lblSaldo3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblSaldo3.setForeground(new java.awt.Color(51, 0, 102));
        lblSaldo3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSaldo3.setText("$0.0");
        dTran.getContentPane().add(lblSaldo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 130, 30));

        jLabel22.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 153, 153));
        jLabel22.setText("Cuenta a transferir");
        dTran.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 230, 30));

        dTran.getContentPane().add(cbTran, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 180, 150, -1));

        jLabel24.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 153, 153));
        jLabel24.setText("Cantidad a tranferir");
        dTran.getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 240, 30));

        jLabel20.setBackground(new java.awt.Color(123, 202, 206));
        jLabel20.setText(" ");
        jLabel20.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(0, 102, 102)), "Transferir", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 24), new java.awt.Color(0, 102, 102))); // NOI18N
        jLabel20.setOpaque(true);
        dTran.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 340));

        dEditC.setMinimumSize(new java.awt.Dimension(750, 500));
        dEditC.setPreferredSize(new java.awt.Dimension(684, 427));
        dEditC.getContentPane().setLayout(null);

        btnEdit.setBackground(new java.awt.Color(102, 0, 255));
        btnEdit.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Limpiar historial");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        dEditC.getContentPane().add(btnEdit);
        btnEdit.setBounds(420, 380, 240, 30);

        jTable1.setBackground(new java.awt.Color(103, 142, 181));
        jTable1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(200, 200, 251));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Movimiento", "Fechan", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        dEditC.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 50, 620, 320);

        jLabel27.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 153, 153));
        jLabel27.setText("Apellido Materno");
        dEditC.getContentPane().add(jLabel27);
        jLabel27.setBounds(70, 190, 160, 30);

        fondo.setBackground(new java.awt.Color(123, 202, 206));
        fondo.setText(" ");
        fondo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(0, 102, 102)), "Historial", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 24), new java.awt.Color(0, 102, 102))); // NOI18N
        fondo.setOpaque(true);
        dEditC.getContentPane().add(fondo);
        fondo.setBounds(0, 0, 690, 430);

        dEditC1.setMinimumSize(new java.awt.Dimension(750, 500));
        dEditC1.setPreferredSize(new java.awt.Dimension(684, 427));
        dEditC1.getContentPane().setLayout(null);

        jLabel29.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(102, 102, 102));
        jLabel29.setText("Modifica tus datos tus datos");
        dEditC1.getContentPane().add(jLabel29);
        jLabel29.setBounds(30, 40, 180, 30);

        txtNombre1.setBackground(new java.awt.Color(53, 66, 78));
        txtNombre1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtNombre1.setForeground(new java.awt.Color(140, 213, 253));
        txtNombre1.setText(" ");
        dEditC1.getContentPane().add(txtNombre1);
        txtNombre1.setBounds(240, 90, 330, 29);

        jLabel30.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 153, 153));
        jLabel30.setText("Apellido Paterno");
        dEditC1.getContentPane().add(jLabel30);
        jLabel30.setBounds(70, 140, 150, 30);

        txtApP1.setBackground(new java.awt.Color(53, 66, 78));
        txtApP1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtApP1.setForeground(new java.awt.Color(140, 213, 253));
        txtApP1.setText(" ");
        dEditC1.getContentPane().add(txtApP1);
        txtApP1.setBounds(240, 140, 330, 29);

        jLabel31.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 153, 153));
        jLabel31.setText("NIP");
        dEditC1.getContentPane().add(jLabel31);
        jLabel31.setBounds(70, 240, 160, 30);

        btnNip1.setBackground(new java.awt.Color(53, 66, 78));
        btnNip1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnNip1.setForeground(new java.awt.Color(140, 213, 253));
        btnNip1.setText(" ");
        dEditC1.getContentPane().add(btnNip1);
        btnNip1.setBounds(240, 240, 330, 29);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha de Nacimeinto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16), new java.awt.Color(0, 131, 204))); // NOI18N
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 153, 153));
        jLabel32.setText("Dia");
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 90, 30));

        jLabel33.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 153, 153));
        jLabel33.setText("Año");
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 110, 30));

        jLabel34.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 153, 153));
        jLabel34.setText("Mes");
        jPanel3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 110, 30));

        cbAño1.setBackground(new java.awt.Color(53, 66, 78));
        cbAño1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        cbAño1.setForeground(new java.awt.Color(140, 213, 253));
        cbAño1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005" }));
        jPanel3.add(cbAño1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        cbDia1.setBackground(new java.awt.Color(53, 66, 78));
        cbDia1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        cbDia1.setForeground(new java.awt.Color(140, 213, 253));
        cbDia1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cbDia1.setOpaque(false);
        jPanel3.add(cbDia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        cbMes1.setBackground(new java.awt.Color(53, 66, 78));
        cbMes1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        cbMes1.setForeground(new java.awt.Color(140, 213, 253));
        cbMes1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "enero", "febrero", "marzo", "abril", "mayo", "junio", "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre" }));
        jPanel3.add(cbMes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        dEditC1.getContentPane().add(jPanel3);
        jPanel3.setBounds(70, 280, 510, 100);

        jLabel35.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 153, 153));
        jLabel35.setText("Nombre");
        dEditC1.getContentPane().add(jLabel35);
        jLabel35.setBounds(80, 90, 130, 30);

        btnEdit1.setBackground(new java.awt.Color(102, 0, 255));
        btnEdit1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnEdit1.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit1.setText("Editar Cuenta");
        btnEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit1ActionPerformed(evt);
            }
        });
        dEditC1.getContentPane().add(btnEdit1);
        btnEdit1.setBounds(420, 380, 240, 30);

        jLabel36.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 153, 153));
        jLabel36.setText("Apellido Materno");
        dEditC1.getContentPane().add(jLabel36);
        jLabel36.setBounds(70, 190, 160, 30);

        txtApM2.setBackground(new java.awt.Color(53, 66, 78));
        txtApM2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtApM2.setForeground(new java.awt.Color(140, 213, 253));
        txtApM2.setText(" ");
        dEditC1.getContentPane().add(txtApM2);
        txtApM2.setBounds(240, 190, 330, 29);

        fondo1.setBackground(new java.awt.Color(123, 202, 206));
        fondo1.setText(" ");
        fondo1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(0, 102, 102)), "Editar Cuenta", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 24), new java.awt.Color(0, 102, 102))); // NOI18N
        fondo1.setOpaque(true);
        dEditC1.getContentPane().add(fondo1);
        fondo1.setBounds(0, 0, 690, 430);

        jLabel37.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 153, 153));
        jLabel37.setText("Apellido Materno");
        dEditC1.getContentPane().add(jLabel37);
        jLabel37.setBounds(70, 190, 160, 30);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menu1.setBackground(new java.awt.Color(103, 142, 181));
        menu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(165, 243, 219), 5));
        menu1.setMinimumSize(new java.awt.Dimension(800, 600));
        menu1.setOpaque(true);
        menu1.setPreferredSize(new java.awt.Dimension(800, 600));
        menu1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDep.setBackground(new java.awt.Color(63, 63, 150));
        btnDep.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnDep.setForeground(new java.awt.Color(255, 255, 255));
        btnDep.setText("Depositar");
        btnDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepActionPerformed(evt);
            }
        });
        menu1.add(btnDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 127, 275, 91));

        btnSalir.setBackground(new java.awt.Color(255, 51, 51));
        btnSalir.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        menu1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 535, 133, 44));

        btnTra.setBackground(new java.awt.Color(63, 63, 150));
        btnTra.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnTra.setForeground(new java.awt.Color(255, 255, 255));
        btnTra.setText("Transferir");
        btnTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraActionPerformed(evt);
            }
        });
        menu1.add(btnTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 236, 275, 91));

        btnGenera4.setBackground(new java.awt.Color(63, 63, 150));
        btnGenera4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnGenera4.setForeground(new java.awt.Color(255, 255, 255));
        btnGenera4.setText("Eliminar cuenta");
        btnGenera4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenera4ActionPerformed(evt);
            }
        });
        menu1.add(btnGenera4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 275, 91));

        btnHis.setBackground(new java.awt.Color(63, 63, 150));
        btnHis.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnHis.setForeground(new java.awt.Color(255, 255, 255));
        btnHis.setText("Historial");
        btnHis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHisActionPerformed(evt);
            }
        });
        menu1.add(btnHis, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 356, 275, 91));

        jLabel2.setBackground(new java.awt.Color(123, 202, 206));
        jLabel2.setText(" ");
        jLabel2.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(87, 95, 98));
        jPanel1.setForeground(new java.awt.Color(77, 72, 72));

        jLabel1.setBackground(new java.awt.Color(102, 255, 255));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 204, 255));
        jLabel1.setText("Bienvenido,");

        jLabel3.setBackground(new java.awt.Color(102, 255, 255));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 204, 255));
        jLabel3.setText("Nombre");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(315, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(528, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jLabel1)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        btnRe.setBackground(new java.awt.Color(63, 63, 150));
        btnRe.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnRe.setForeground(new java.awt.Color(255, 255, 255));
        btnRe.setText("Retirar");
        btnRe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReActionPerformed(evt);
            }
        });

        btnEdC.setBackground(new java.awt.Color(63, 63, 150));
        btnEdC.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnEdC.setForeground(new java.awt.Color(255, 255, 255));
        btnEdC.setText("Editar cuenta");
        btnEdC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEdC, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRe, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnRe, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEdC, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(288, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepActionPerformed
        
    }//GEN-LAST:event_btnDepActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
     
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnReActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReActionPerformed

    private void btnEdCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEdCActionPerformed

    private void btnTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTraActionPerformed

    private void btnGenera4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenera4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenera4ActionPerformed

    private void btnHisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHisActionPerformed

    private void btnDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDepositarActionPerformed

    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRetirarActionPerformed

    private void btnRetirar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRetirar2ActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEdit1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(m2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(m2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(m2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(m2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new m2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDep;
    private javax.swing.JButton btnDepositar;
    private javax.swing.JButton btnEdC;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEdit1;
    private javax.swing.JButton btnGenera4;
    private javax.swing.JButton btnHis;
    private javax.swing.JTextField btnNip1;
    private javax.swing.JButton btnRe;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JButton btnRetirar2;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTra;
    private javax.swing.JComboBox<String> cbAño1;
    private javax.swing.JComboBox<String> cbDia1;
    private javax.swing.JComboBox<String> cbMes1;
    private javax.swing.JComboBox<String> cbTran;
    private javax.swing.JDialog dDep;
    private javax.swing.JDialog dEditC;
    private javax.swing.JDialog dEditC1;
    private javax.swing.JDialog dRet;
    private javax.swing.JDialog dTran;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblSaldo1;
    private javax.swing.JLabel lblSaldo3;
    private javax.swing.JLayeredPane menu1;
    private javax.swing.JSpinner sDep;
    private javax.swing.JSpinner sRet;
    private javax.swing.JSpinner sTran;
    private javax.swing.JTextField txtApM2;
    private javax.swing.JTextField txtApP1;
    private javax.swing.JTextField txtNombre1;
    // End of variables declaration//GEN-END:variables
}
